version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - portx-iam
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - portx-iam
    restart: unless-stopped
  
  keycloak:
    container_name: keycloak
    image: "quay.io/keycloak/keycloak:19.0.3"
    depends_on:
      - "postgres"
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=${KEYCLOAK_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_DB_SCHEMA=public
      - KC_DB_URL_DATABASE=${POSTGRES_DB}
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_HOSTNAME=id.keycloak.test:8443
      - KC_HOSTNAME_STRICT=false
      - KC_HTTPS_CLIENT_AUTH=request
      - KC_HTTP_ENABLED="true"
      - KC_HTTP_PORT=8080
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key.pem
      - KC_HTTPS_PORT=8443
      - KC_HTTPS_PROTOCOLS=TLSv1.3,TLSv1.2
#      - KC_FEATURES: authorization token-exchange docker impersonation scripts upload-scripts web-authn client-policies dynamic-scopes
    ports:
      - "${KEYCLOAK_HTTP_PORT:-8080}:8080"
      - "${KEYCLOAK_HTTPS_PORT:-8443}:8443"
    restart: unless-stopped
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start --proxy=edge"]
    volumes:
      - ./keycloak_data/id.keycloak.test+1.pem:/opt/keycloak/conf/server.crt.pem
      - ./keycloak_data/id.keycloak.test+1-key.pem:/opt/keycloak/conf/server.key.pem
    networks:
      - portx-iam
  
networks:
  portx-iam:
    driver: bridge

volumes:
    postgres:
    pgadmin: